include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/main/plugin.yml"

variables:
  # To reduce the licenses used.
  PYTEST_NUM_PROCESSES: 1

test:
  rules:
    - when: never

.test:
  extends:
    - .test-base
  rules:
    # We only have access to matlab internally,
    # the tests are executed on the internal gitlab.
    - if: $CI_SERVER_HOST == "gitlab.com"
      when: never
    - !reference [.test-base, rules]
  image:
    name: registry.gitlab.com/gemseo/dev/gemseo-matlab/multi-python-matlab:$MATLAB_VERSION
  tags:
    - saas-linux-small-amd64

test-r2021b-py39:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2021b
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.11.0

test-r2022a-py39:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2022a
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.12.0
  needs:
    - test-r2021b-py39

test-r2022b-py39:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2022b
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.13.0
  needs:
    - test-r2022a-py39

test-r2022b-py310:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py310-coverage
    MATLAB_VERSION: r2022b
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.13.0
  needs:
    - test-r2022b-py39

test-r2023a-py39:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2023a
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.14.0
  needs:
    - test-r2022b-py310

test-r2023a-py310:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py310-coverage
    MATLAB_VERSION: r2023a
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.14.0
  needs:
    - test-r2023a-py39

test-r2023b-py39:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2023b
    MATLAB_PIP_REQ_SPEC: matlabengine~=23.2.0
  needs:
    - test-r2023a-py310

test-r2023b-py310:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py310-coverage
    MATLAB_VERSION: r2023b
    MATLAB_PIP_REQ_SPEC: matlabengine~=23.2.0
  needs:
    - test-r2023b-py39

test-r2023b-py311:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py311-coverage
    MATLAB_VERSION: r2023b
    MATLAB_PIP_REQ_SPEC: matlabengine~=23.2.0
  needs:
    - test-r2023b-py310

test-r2024a-py39:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2024a
    MATLAB_PIP_REQ_SPEC: matlabengine~=24.1.0
  needs:
    - test-r2023b-py311

test-r2024a-py310:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py310-coverage
    MATLAB_VERSION: r2024a
    MATLAB_PIP_REQ_SPEC: matlabengine~=24.1.0
  needs:
    - test-r2024a-py39

test-r2024a-py311:
  extends:
    - .test
  variables:
    TOX_ENV_NAME: py311-coverage
    MATLAB_VERSION: r2024a
    MATLAB_PIP_REQ_SPEC: matlabengine~=24.1.0
  needs:
    - test-r2024a-py310

# Windows.

test-r2022a-py39-windows:
  extends:
    - .test
  tags:
    - windows-server-2019
  variables:
    TOX_ENV_NAME: py39-coverage
    MATLAB_VERSION: r2022a
    MATLAB_PIP_REQ_SPEC: matlabengine~=9.12.0
  needs:
    - test-r2024a-py311
