include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/main/plugin.yml"

variables:
  # To reduce the licenses used.
  PYTEST_NUM_PROCESSES: 1

test:
  rules:
    # We only have access to matlab internally,
    # the tests are executed on the internal gitlab.
    - if: $CI_SERVER_HOST == "gitlab.com"
      when: never
    - !reference [.test-base, rules]
  extends:
    - .test-base
  parallel:
    matrix:
      - TAG: saas-linux-small-amd64
        MATLAB_VERSION: r2021b
        MATLAB_PIP_REQ_SPEC: matlabengine~=9.11.0
        TOX_ENV_NAME:
          - py39-coverage
      - TAG: saas-linux-small-amd64
        MATLAB_VERSION: r2022a
        MATLAB_PIP_REQ_SPEC: matlabengine~=9.12.0
        TOX_ENV_NAME:
          - py39-coverage
      - TAG: saas-linux-small-amd64
        MATLAB_VERSION: r2022b
        MATLAB_PIP_REQ_SPEC: matlabengine~=9.13.0
        TOX_ENV_NAME:
          - py39-coverage
          - py310-coverage
      - TAG: saas-linux-small-amd64
        MATLAB_VERSION: r2023a
        MATLAB_PIP_REQ_SPEC: matlabengine~=9.14.0
        TOX_ENV_NAME:
          - py39-coverage
          - py310-coverage
      - TAG: saas-linux-small-amd64
        MATLAB_VERSION: r2023b
        MATLAB_PIP_REQ_SPEC: matlabengine~=23.2.0
        TOX_ENV_NAME:
          - py39-coverage
          - py310-coverage
          - py311-coverage
      - TAG: saas-linux-small-amd64
        MATLAB_VERSION: r2024a
        MATLAB_PIP_REQ_SPEC: matlabengine~=24.1.0
        TOX_ENV_NAME:
          - py39-coverage
          - py310-coverage
          - py311-coverage

      # This version is not yet available on windows.
      # - TAG: windows-server-2019
      #   MATLAB_VERSION: r2021b
      #   MATLAB_PIP_REQ_SPEC: matlabengine~=9.11.0
      #   TOX_ENV_NAME:
      #     - py38-coverage
      #     - py39-coverage
      - TAG: windows-server-2019
        MATLAB_VERSION: r2022a
        MATLAB_PIP_REQ_SPEC: matlabengine~=9.12.0
        TOX_ENV_NAME:
          - py39-coverage
  tags:
    - $TAG
  image:
    name: registry.gitlab.com/gemseo/dev/gemseo-matlab/multi-python-matlab:$MATLAB_VERSION
