include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/main/plugin.yml"

test:
  extends:
    - .test-base
  parallel:
    matrix:
      - TAG: docker
        MATLAB_VERSION: r2020b
        MATLAB_PIP_REQ_SPEC: matlabengine==9.9.1
        TOX_ENV_NAME:
          - py38-coverage
      - TAG: docker
        MATLAB_VERSION: r2021a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.10.1
        TOX_ENV_NAME:
          - py38-coverage
      - TAG: docker
        MATLAB_VERSION: r2021b
        MATLAB_PIP_REQ_SPEC: matlabengine==9.11.19
        TOX_ENV_NAME:
          - py38-coverage
          - py39-coverage
      - TAG: docker
        MATLAB_VERSION: r2022a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.12.17
        TOX_ENV_NAME:
          - py38-coverage
          - py39-coverage

      - TAG: windows-server-2019
        MATLAB_VERSION: r2020b
        MATLAB_PIP_REQ_SPEC: matlabengine==9.9.1
        TOX_ENV_NAME:
          - py38-coverage
      - TAG: windows-server-2019
        MATLAB_VERSION: r2021a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.10.1
        TOX_ENV_NAME:
          - py38-coverage
      # This version is not yet available on windows.
      # - TAG: windows-server-2019
      #   MATLAB_VERSION: r2021b
      #   MATLAB_PIP_REQ_SPEC: matlabengine==9.11.19
      #   TOX_ENV_NAME:
      #     - py38-coverage
      #     - py39-coverage
      - TAG: windows-server-2019
        MATLAB_VERSION: r2022a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.12.17
        TOX_ENV_NAME:
          - py38-coverage
          - py39-coverage

    # No licence yet for the following versions:
    # r2022b: py38,py39,py310 MATLAB_PIP_REQ_SPEC='matlabengine==9.13.7'
    # r2023a: py38,py39,py310 MATLAB_PIP_REQ_SPEC='matlabengine==9.14.2'
  tags:
    - $TAG
  image:
    name: registry.gitlab.com/gemseo/dev/gemseo-matlab/multi-python-matlab:$MATLAB_VERSION
