include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/py311/plugin.yml"

test:
  rules:
    # We only have access to matlab internally,
    # the tests are executed on the internal gitlab.
    - if: $CI_SERVER_HOST == "gitlab.com"
      when: never
    - !reference [.test-base, rules]
  extends:
    - .test-base
  parallel:
    matrix:
      - TAG: docker
        MATLAB_VERSION: r2021b
        MATLAB_PIP_REQ_SPEC: matlabengine==9.11.19
        TOX_ENV_NAME:
          - py39-coverage
      - TAG: docker
        MATLAB_VERSION: r2022a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.12.17
        TOX_ENV_NAME:
          - py39-coverage
      - TAG: docker
        MATLAB_VERSION: r2022b
        MATLAB_PIP_REQ_SPEC: matlabengine==9.13.9
        TOX_ENV_NAME:
          - py39-coverage
          - py310-coverage
      - TAG: docker
        MATLAB_VERSION: r2023a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.14.3
        TOX_ENV_NAME:
          - py39-coverage
          - py310-coverage

      # This version is not yet available on windows.
      # - TAG: windows-server-2019
      #   MATLAB_VERSION: r2021b
      #   MATLAB_PIP_REQ_SPEC: matlabengine==9.11.19
      #   TOX_ENV_NAME:
      #     - py38-coverage
      #     - py39-coverage
      - TAG: windows-server-2019
        MATLAB_VERSION: r2022a
        MATLAB_PIP_REQ_SPEC: matlabengine==9.12.17
        TOX_ENV_NAME:
          - py39-coverage
  tags:
    - $TAG
  image:
    name: registry.gitlab.com/gemseo/dev/gemseo-matlab/multi-python-matlab:$MATLAB_VERSION
